#!/bin/sh -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
    update-alternatives --remove x-www-browser /opt/firefox/firefox
    update-alternatives --remove gnome-www-browser /opt/firefox/firefox
fi

